# To use:
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate scipy-dev
#
# Also used to build the `scipy-dev` Docker image via GitHub Actions
name: scipy-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - setuptools<60.0
  - cython
  - compilers
  - meson>=0.64.0
  - meson-python
  - ninja
  - numpy
  - openblas
  - libblas=*=*openblas  # helps avoid pulling in MKL
  - pybind11
